name: aplikasi_kalkulator
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  math_expressions: ^2.6.0
  flutter_native_splash: ^2.4.4
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.jpg.jpeg  # Sesuaikan dengan nama file yang benar
    - assets/images/profile.jpg.jpeg  # Sesuaikan dengan nama file yang benar

flutter_native_splash:
  color: "#ffffff"  # Bisa diganti warna lain
  image: assets/images/background.jpg.jpeg  # Sesuaikan dengan nama file yang benar
  android: true
  ios: true
  web: false
